---
- become: true
  hosts: cluster_master_node
  tasks:
    - name: Include variables
      include_vars: ../vars/galera_cluster_variables.yml
    - name: Include encrypted variables
      include_vars: ../vars/user_passwords.yml
    - name: uncomment the wsrep_provider_options="pc.bootstrap=true"
      replace:
          path: /etc/my.cnf.d/server.cnf
          regexp:  '#wsrep_provider_options="pc.bootstrap=true"'
          replace: 'wsrep_provider_options="pc.bootstrap=true"'
          backup: yes
    - name: Start MySQL/MariaDB using /etc/init.d/mysql start --wsrep-new-cluster command for first node.
      #service:
      #  name: mysql
      #  state: started
      #  arguments: "--wsrep-new-cluster"
      command: '/etc/init.d/mysql start --wsrep-new-cluster'
